import styles from "./FAQPage.module.css";
import { Container, Row, Col } from "reactstrap";
import { useState } from "react";

const faqCategories = [
    {
        heading: "General",
        questions: [
            {
                question: "What is ChromoXplorer?",
                answer:
                    "ChromoXplorer is a 3D genome visualization platform that renders chromosome structures as interactive three-dimensional scenes. It reads PDB files of modeled chromosomes and displays all of them together — giving researchers and students a spatial view of the entire genome that no 2D tool can provide.",
            },
            {
                question: "Who is ChromoXplorer for?",
                answer:
                    "ChromoXplorer is designed for researchers, bioinformaticians, educators, and students interested in genome architecture, chromatin organization, and the relationship between genome structure and gene regulation.",
            },
            {
                question: "Does ChromoXplorer require any installation?",
                answer:
                    "No. ChromoXplorer runs entirely in your web browser — no software installation or local environment setup is needed.",
            },
        ],
    },
    {
        heading: "Data & File Formats",
        questions: [
            {
                question: "What file format does ChromoXplorer use?",
                answer:
                    "ChromoXplorer reads PDB (Protein Data Bank) files that encode the three-dimensional spatial coordinates of chromosome structures. These files are typically generated by processing Hi-C contact data through 3D modeling pipelines.",
            },
            {
                question: "What is a PDB file in the context of genomes?",
                answer:
                    "PDB format was originally designed for protein structures, but it can also represent any set of 3D coordinates. In genomics, computational tools can model how chromosomes fold in 3D space from Hi-C contact data and output those structures as PDB files, which ChromoXplorer then renders.",
            },
            {
                question: "What is Hi-C data?",
                answer:
                    "Hi-C is a chromosome conformation capture technique that measures how often pairs of genomic loci are physically close to each other inside the nucleus. The resulting contact matrices capture the 3D folding of the genome and are commonly stored in cooler file format (.cool / .mcool).",
            },
            {
                question: "Can I upload my own data?",
                answer:
                    "Yes — with a Researcher account. You can upload your own PDB files and render them directly in the explorer. Your data is never saved to our servers; it is processed entirely within your browser session.",
            },
        ],
    },
    {
        heading: "Access & Pricing",
        questions: [
            {
                question: "Is ChromoXplorer free to use?",
                answer:
                    "Yes. The Free tier gives you full access to the 3D explorer using our curated collection of publicly available chromosome datasets, with no account required.",
            },
            {
                question: "What does the Researcher plan include?",
                answer:
                    "The Researcher plan adds the ability to load your own PDB files into the explorer for on-demand visualization. Your uploaded data is never stored — it exists only for the duration of your session.",
            },
            {
                question: "How do I get a Researcher account?",
                answer:
                    "Contact us through the Support page and we will get you set up. See the Pricing page for a full comparison of what each plan includes.",
            },
        ],
    },
];

function FAQItem({ question, answer }) {
    const [isOpen, setIsOpen] = useState(false);

    return (
        <div className={`${styles.faqItem} ${isOpen ? styles.faqItemOpen : ""}`}>
            <button
                className={styles.faqQuestion}
                onClick={() => setIsOpen(!isOpen)}
                aria-expanded={isOpen}
            >
                <span>{question}</span>
                <span className={`${styles.faqChevron} ${isOpen ? styles.faqChevronOpen : ""}`}>
                    ›
                </span>
            </button>
            {isOpen && (
                <div className={styles.faqAnswer}>
                    <p>{answer}</p>
                </div>
            )}
        </div>
    );
}

export default function FAQPage() {
    return (
        <>
            {/* HERO */}
            <div className={styles.hero}>
                <Container className={styles.heroContent}>
                    <h1 className={styles.heroTitle}>Frequently Asked Questions</h1>
                    <p className={styles.heroSubtitle}>
                        Quick answers to common questions about ChromoXplorer.
                    </p>
                </Container>
            </div>

            {/* FAQ CATEGORIES */}
            {faqCategories.map((category, ci) => (
                <div key={ci} className={styles.categorySection}>
                    <Container>
                        <Row className="justify-content-center">
                            <Col lg={8}>
                                <h2 className={styles.categoryHeading}>{category.heading}</h2>
                                <div className={styles.faqList}>
                                    {category.questions.map((item, qi) => (
                                        <FAQItem
                                            key={qi}
                                            question={item.question}
                                            answer={item.answer}
                                        />
                                    ))}
                                </div>
                            </Col>
                        </Row>
                    </Container>
                </div>
            ))}

            {/* STILL HAVE QUESTIONS */}
            <div className={styles.closingSection}>
                <Container className={styles.closingContent}>
                    <h2 className={styles.closingHeading}>Still have questions?</h2>
                    <p className={styles.closingBody}>
                        If you didn't find what you were looking for, our support team is happy to help.
                    </p>
                    <a href="/support" className={styles.closingButton}>
                        Contact Support
                    </a>
                </Container>
            </div>
        </>
    );
}
